version: '3'
services:
  db:
    container_name: timetrack-app-db
    image: postgres
    restart: always
    env_file: .env
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    networks:
      - timetracker_app_api
  pgamin:
    container_name: timetracker-app-pgadmin4
    image: dpage/pgadmin4
    restart: always
    env_file: .env
    ports:
      - '${WEBSERVER_PORT}:${PGADMIN_LISTEN_PORT}'
    volumes:
      - ./pgadmin-data:/var/lib/pgadmin # Named volumn in container
    depends_on:
      - db
    networks:
      - timetracker_app_api
  dev:
    container_name: timetrack-app-dev
    image: timetrack-app-api
    env_file: .env
    build:
      context: .
      dockerfile: ./dockerfiles/dev.Dockerfile
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - '${APP_PORT}:${APP_PORT}'
    depends_on:
      - db
    restart: unless-stopped
    networks:
      - timetracker_app_api
networks:
  timetracker_app_api:
volumes:
  pgdata:
  pgadmin-data:
